<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SystemSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // Icons & Logos
            [
                'key' => 'site.favicon',
                'name' => 'Favicon (ICO Icon)',
                'value' => 'build/images/favicon.ico',
                'type' => 'file',
                'group' => 'Branding',
                'is_locked' => false,
            ],
            [
                'key' => 'site.sidebar_logo',
                'name' => 'Sidebar Logo',
                'value' => 'build/images/smart-logo-sm3.png',
                'type' => 'file',
                'group' => 'Branding',
                'is_locked' => false,
            ],
            [
                'key' => 'site.login_logo',
                'name' => 'Login Page Logo',
                'value' => 'build/images/smart-logo-sm3.png',
                'type' => 'file',
                'group' => 'Branding',
                'is_locked' => false,
            ],
            [
                'key' => 'site.landing_logo_dark',
                'name' => 'Landing Page Logo (Dark)',
                'value' => 'build/images/smart-logo-dark.png',
                'type' => 'file',
                'group' => 'Branding',
                'is_locked' => false,
            ],
            [
                'key' => 'site.landing_logo_light',
                'name' => 'Landing Page Logo (Light)',
                'value' => 'build/images/smart-logo-light.png',
                'type' => 'file',
                'group' => 'Branding',
                'is_locked' => false,
            ],

            // Site Information
            [
                'key' => 'site.name',
                'name' => 'Site Name',
                'value' => 'eSMART Campus',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'site.short_name',
                'name' => 'Site Short Name',
                'value' => 'smart',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'site.tagline',
                'name' => 'Site Tagline',
                'value' => 'The better way to manage your campus',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'site.description',
                'name' => 'Site Description',
                'value' => 'eSMART Campus is a comprehensive student management system designed to streamline campus operations, student enrollment, attendance tracking, and academic management.',
                'type' => 'textarea',
                'group' => 'General',
                'is_locked' => false,
            ],

            // Footer
            [
                'key' => 'site.footer_text',
                'name' => 'Footer Text',
                'value' => 'eSMART Campus. Crafted with ❤️ by eSMART Campus Team',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],

            // Theme Settings
            [
                'key' => 'theme.layout',
                'name' => 'Layout',
                'value' => 'vertical',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.topbar',
                'name' => 'Topbar Style',
                'value' => 'light',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.sidebar',
                'name' => 'Sidebar Style',
                'value' => 'dark',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.sidebar_size',
                'name' => 'Sidebar Size',
                'value' => 'lg',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.sidebar_image',
                'name' => 'Sidebar Image',
                'value' => 'none',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.preloader',
                'name' => 'Preloader',
                'value' => 'disable',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.theme',
                'name' => 'Theme',
                'value' => 'default',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],
            [
                'key' => 'theme.theme_colors',
                'name' => 'Theme Colors',
                'value' => 'default',
                'type' => 'text',
                'group' => 'General',
                'is_locked' => false,
            ],

            // Login/Register Pages
            [
                'key' => 'auth.welcome_message',
                'name' => 'Login Welcome Message',
                'value' => 'Welcome Back !',
                'type' => 'text',
                'group' => 'Authentication',
                'is_locked' => false,
            ],
            [
                'key' => 'auth.login_subtitle',
                'name' => 'Login Page Subtitle',
                'value' => 'Sign in to continue to eSMART Campus.',
                'type' => 'text',
                'group' => 'Authentication',
                'is_locked' => false,
            ],
            [
                'key' => 'auth.register_title',
                'name' => 'Register Page Title',
                'value' => 'Create New Account',
                'type' => 'text',
                'group' => 'Authentication',
                'is_locked' => false,
            ],
            [
                'key' => 'auth.register_subtitle',
                'name' => 'Register Page Subtitle',
                'value' => 'Get your free eSMART Campus account now',
                'type' => 'text',
                'group' => 'Authentication',
                'is_locked' => false,
            ],

            // Landing Page Quotes
            [
                'key' => 'landing.quote_1',
                'name' => 'Landing Page Quote 1',
                'value' => 'Sa Manongol High, Gaganda ang Buhay!',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.quote_2',
                'name' => 'Landing Page Quote 2',
                'value' => 'Manage your campus tasks in one unified place.',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.quote_3',
                'name' => 'Landing Page Quote 3',
                'value' => 'SMART Campus keeps everyone connected and informed.',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Carousel Images
            [
                'key' => 'landing.carousel_image_1',
                'name' => 'Carousel Image 1 (Default)',
                'value' => 'build/images/demos/default.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_2',
                'name' => 'Carousel Image 2 (SaaS)',
                'value' => 'build/images/demos/saas.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_3',
                'name' => 'Carousel Image 3 (Material)',
                'value' => 'build/images/demos/material.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_4',
                'name' => 'Carousel Image 4 (Minimal)',
                'value' => 'build/images/demos/minimal.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_5',
                'name' => 'Carousel Image 5 (Creative)',
                'value' => 'build/images/demos/creative.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_6',
                'name' => 'Carousel Image 6 (Modern)',
                'value' => 'build/images/demos/modern.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.carousel_image_7',
                'name' => 'Carousel Image 7 (Interactive)',
                'value' => 'build/images/demos/interactive.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Client/Trusted Partner Logos
            [
                'key' => 'landing.client_logo_1',
                'name' => 'Client Logo 1 (Amazon)',
                'value' => 'build/images/clients/amazon.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.client_logo_2',
                'name' => 'Client Logo 2 (Walmart)',
                'value' => 'build/images/clients/walmart.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.client_logo_3',
                'name' => 'Client Logo 3 (Lenovo)',
                'value' => 'build/images/clients/lenovo.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.client_logo_4',
                'name' => 'Client Logo 4 (PayPal)',
                'value' => 'build/images/clients/paypal.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.client_logo_5',
                'name' => 'Client Logo 5 (Shopify)',
                'value' => 'build/images/clients/shopify.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.client_logo_6',
                'name' => 'Client Logo 6 (Verizon)',
                'value' => 'build/images/clients/verizon.svg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Services Section
            [
                'key' => 'landing.services_title',
                'name' => 'Services Section Title',
                'value' => 'A Digital web design studio creating modern & engaging online',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.services_description',
                'name' => 'Services Section Description',
                'value' => 'To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce the grammar',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 1
            [
                'key' => 'landing.service_1_title',
                'name' => 'Service 1 Title',
                'value' => 'Creative Design',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_1_description',
                'name' => 'Service 1 Description',
                'value' => 'The creative design includes designs that are unique, effective and memorable.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_1_icon',
                'name' => 'Service 1 Icon Class',
                'value' => 'ri-pencil-ruler-2-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_1_link',
                'name' => 'Service 1 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 2
            [
                'key' => 'landing.service_2_title',
                'name' => 'Service 2 Title',
                'value' => 'Unlimited Colors',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_2_description',
                'name' => 'Service 2 Description',
                'value' => 'The collection of rules and guidelines which designers use to communicate with users through appealing.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_2_icon',
                'name' => 'Service 2 Icon Class',
                'value' => 'ri-palette-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_2_link',
                'name' => 'Service 2 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 3
            [
                'key' => 'landing.service_3_title',
                'name' => 'Service 3 Title',
                'value' => 'Strategy Solutions',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_3_description',
                'name' => 'Service 3 Description',
                'value' => 'Business development firm that provides strategic planning, market research services and project.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_3_icon',
                'name' => 'Service 3 Icon Class',
                'value' => 'ri-lightbulb-flash-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_3_link',
                'name' => 'Service 3 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 4
            [
                'key' => 'landing.service_4_title',
                'name' => 'Service 4 Title',
                'value' => 'Awesome Support',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_4_description',
                'name' => 'Service 4 Description',
                'value' => 'Awesome Support is the most versatile and feature-rich support plugin for all version.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_4_icon',
                'name' => 'Service 4 Icon Class',
                'value' => 'ri-customer-service-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_4_link',
                'name' => 'Service 4 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 5
            [
                'key' => 'landing.service_5_title',
                'name' => 'Service 5 Title',
                'value' => 'Truly Multipurpose',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_5_description',
                'name' => 'Service 5 Description',
                'value' => 'You usually get a broad range of options to play with. This enables you to use a single theme across multiple.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_5_icon',
                'name' => 'Service 5 Icon Class',
                'value' => 'ri-stack-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_5_link',
                'name' => 'Service 5 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 6
            [
                'key' => 'landing.service_6_title',
                'name' => 'Service 6 Title',
                'value' => 'Easy to customize',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_6_description',
                'name' => 'Service 6 Description',
                'value' => 'Personalise your own website, no matter what theme and what customization options.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_6_icon',
                'name' => 'Service 6 Icon Class',
                'value' => 'ri-settings-2-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_6_link',
                'name' => 'Service 6 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 7
            [
                'key' => 'landing.service_7_title',
                'name' => 'Service 7 Title',
                'value' => 'Responsive & Clean Design',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_7_description',
                'name' => 'Service 7 Description',
                'value' => 'Responsive design is a graphic user interface (GUI) design approach used to create content.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_7_icon',
                'name' => 'Service 7 Icon Class',
                'value' => 'ri-slideshow-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_7_link',
                'name' => 'Service 7 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 8
            [
                'key' => 'landing.service_8_title',
                'name' => 'Service 8 Title',
                'value' => 'Google Font Collection',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_8_description',
                'name' => 'Service 8 Description',
                'value' => 'Google Fonts is a collection of 915 fonts, all available to use for free on your website.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_8_icon',
                'name' => 'Service 8 Icon Class',
                'value' => 'ri-google-fill',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_8_link',
                'name' => 'Service 8 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Service 9
            [
                'key' => 'landing.service_9_title',
                'name' => 'Service 9 Title',
                'value' => 'Top Industry Specialists',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_9_description',
                'name' => 'Service 9 Description',
                'value' => 'An industrial specialist works with industrial operations to ensure that manufacturing facilities work.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_9_icon',
                'name' => 'Service 9 Icon Class',
                'value' => 'ri-briefcase-5-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.service_9_link',
                'name' => 'Service 9 Link URL',
                'value' => '#',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Features Section
            [
                'key' => 'landing.feature_image',
                'name' => 'Feature Section Image',
                'value' => 'build/images/landing/features/img-1.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_icon',
                'name' => 'Feature Section Icon Class',
                'value' => 'ri-collage-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_title',
                'name' => 'Feature Section Title',
                'value' => 'Huge collection of widgets',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_description',
                'name' => 'Feature Section Description',
                'value' => 'Collection widgets specialize in displaying many elements of the same type, such as a collection of pictures from a collection of articles from a news app or a collection of messages from a communication app.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_1_value',
                'name' => 'Feature Statistic 1 Value',
                'value' => '5',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_1_label',
                'name' => 'Feature Statistic 1 Label',
                'value' => 'Dashboards',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_2_value',
                'name' => 'Feature Statistic 2 Value',
                'value' => '150+',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_2_label',
                'name' => 'Feature Statistic 2 Label',
                'value' => 'Pages',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_3_value',
                'name' => 'Feature Statistic 3 Value',
                'value' => '7+',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_stat_3_label',
                'name' => 'Feature Statistic 3 Label',
                'value' => 'Functional Apps',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page CTA Section
            [
                'key' => 'landing.cta_title',
                'name' => 'CTA Section Title',
                'value' => 'Build your campus management system with eSMART Campus',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.cta_button_text',
                'name' => 'CTA Button Text',
                'value' => 'Get Started',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.cta_button_link',
                'name' => 'CTA Button Link URL',
                'value' => '/register',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.cta_button_icon',
                'name' => 'CTA Button Icon Class',
                'value' => 'ri-user-add-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Feature Block 1 (Well Designed Dashboards)
            [
                'key' => 'landing.feature_block_1_badge',
                'name' => 'Feature Block 1 Badge',
                'value' => 'Design',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_title',
                'name' => 'Feature Block 1 Title',
                'value' => 'Well Designed Dashboards',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_description',
                'name' => 'Feature Block 1 Description',
                'value' => 'Quality Dashboards (QD) is a condition-specific, actionable web-based application for quality reporting and population management that is integrated into the Electronic Health Record (EHR).',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_image',
                'name' => 'Feature Block 1 Image',
                'value' => 'build/images/landing/features/img-2.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_item_1',
                'name' => 'Feature Block 1 Item 1',
                'value' => 'Ecommerce',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_item_2',
                'name' => 'Feature Block 1 Item 2',
                'value' => 'Analytics',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_item_3',
                'name' => 'Feature Block 1 Item 3',
                'value' => 'CRM',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_item_4',
                'name' => 'Feature Block 1 Item 4',
                'value' => 'Crypto',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_item_5',
                'name' => 'Feature Block 1 Item 5',
                'value' => 'Projects',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_button_text',
                'name' => 'Feature Block 1 Button Text',
                'value' => 'Learn More',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_1_button_link',
                'name' => 'Feature Block 1 Button Link',
                'value' => '/dashboard',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Feature Block 2 (Well Documented)
            [
                'key' => 'landing.feature_block_2_badge',
                'name' => 'Feature Block 2 Badge',
                'value' => 'structure',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_title',
                'name' => 'Feature Block 2 Title',
                'value' => 'Well Documented',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_description',
                'name' => 'Feature Block 2 Description',
                'value' => 'used to describe something that is known about or known to be true because there are many documents that describe it, prove it, etc.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_image',
                'name' => 'Feature Block 2 Image',
                'value' => 'build/images/landing/features/img-3.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_item_1',
                'name' => 'Feature Block 2 Item 1',
                'value' => 'Dynamic Conetnt',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_item_2',
                'name' => 'Feature Block 2 Item 2',
                'value' => 'Setup plugin\'s information.',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.feature_block_2_item_3',
                'name' => 'Feature Block 2 Item 3',
                'value' => 'Themes customization information',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Pricing Section
            [
                'key' => 'landing.pricing_title',
                'name' => 'Pricing Section Title',
                'value' => 'Choose the plan that\'s right for you',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.pricing_description',
                'name' => 'Pricing Section Description',
                'value' => 'Simple pricing. No hidden fees. Advanced features for you business.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.pricing_monthly_label',
                'name' => 'Pricing Monthly Label',
                'value' => 'Month',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.pricing_annual_label',
                'name' => 'Pricing Annual Label',
                'value' => 'Annual',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.pricing_save_percentage',
                'name' => 'Pricing Save Percentage',
                'value' => '20%',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Plan 1 - Basic Plan
            [
                'key' => 'landing.plan_1_name',
                'name' => 'Plan 1 Name',
                'value' => 'Basic Plan',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_subtitle',
                'name' => 'Plan 1 Subtitle',
                'value' => 'For Startup',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_icon',
                'name' => 'Plan 1 Icon Class',
                'value' => 'ri-book-mark-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_price_monthly',
                'name' => 'Plan 1 Monthly Price',
                'value' => '19',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_price_annual',
                'name' => 'Plan 1 Annual Price',
                'value' => '171',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_1',
                'name' => 'Plan 1 Feature 1',
                'value' => 'Upto <b>3</b> Projects',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_2',
                'name' => 'Plan 1 Feature 2',
                'value' => 'Upto <b>299</b> Customers',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_3',
                'name' => 'Plan 1 Feature 3',
                'value' => 'Scalable Bandwidth',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_4',
                'name' => 'Plan 1 Feature 4',
                'value' => '<b>5</b> FTP Login',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_5',
                'name' => 'Plan 1 Feature 5',
                'value' => '<b>24/7</b> Support',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_6',
                'name' => 'Plan 1 Feature 6',
                'value' => '<b>Unlimited</b> Storage',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_7',
                'name' => 'Plan 1 Feature 7',
                'value' => 'Domain',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_5_enabled',
                'name' => 'Plan 1 Feature 5 Enabled',
                'value' => 'false',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_6_enabled',
                'name' => 'Plan 1 Feature 6 Enabled',
                'value' => 'false',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_feature_7_enabled',
                'name' => 'Plan 1 Feature 7 Enabled',
                'value' => 'false',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_button_text',
                'name' => 'Plan 1 Button Text',
                'value' => 'Get Started',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_1_button_link',
                'name' => 'Plan 1 Button Link',
                'value' => 'javascript:void(0);',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Plan 2 - Pro Business
            [
                'key' => 'landing.plan_2_name',
                'name' => 'Plan 2 Name',
                'value' => 'Pro Business',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_subtitle',
                'name' => 'Plan 2 Subtitle',
                'value' => 'Professional plans',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_icon',
                'name' => 'Plan 2 Icon Class',
                'value' => 'ri-medal-fill',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_badge_text',
                'name' => 'Plan 2 Badge Text',
                'value' => 'Popular',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_price_monthly',
                'name' => 'Plan 2 Monthly Price',
                'value' => '29',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_price_annual',
                'name' => 'Plan 2 Annual Price',
                'value' => '261',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_1',
                'name' => 'Plan 2 Feature 1',
                'value' => 'Upto <b>15</b> Projects',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_2',
                'name' => 'Plan 2 Feature 2',
                'value' => '<b>Unlimited</b> Customers',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_3',
                'name' => 'Plan 2 Feature 3',
                'value' => 'Scalable Bandwidth',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_4',
                'name' => 'Plan 2 Feature 4',
                'value' => '<b>12</b> FTP Login',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_5',
                'name' => 'Plan 2 Feature 5',
                'value' => '<b>24/7</b> Support',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_6',
                'name' => 'Plan 2 Feature 6',
                'value' => '<b>Unlimited</b> Storage',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_7',
                'name' => 'Plan 2 Feature 7',
                'value' => 'Domain',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_6_enabled',
                'name' => 'Plan 2 Feature 6 Enabled',
                'value' => 'false',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_feature_7_enabled',
                'name' => 'Plan 2 Feature 7 Enabled',
                'value' => 'false',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_button_text',
                'name' => 'Plan 2 Button Text',
                'value' => 'Get Started',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_2_button_link',
                'name' => 'Plan 2 Button Link',
                'value' => 'javascript:void(0);',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Plan 3 - Platinum Plan
            [
                'key' => 'landing.plan_3_name',
                'name' => 'Plan 3 Name',
                'value' => 'Platinum Plan',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_subtitle',
                'name' => 'Plan 3 Subtitle',
                'value' => 'Enterprise Businesses',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_icon',
                'name' => 'Plan 3 Icon Class',
                'value' => 'ri-stack-fill',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_price_monthly',
                'name' => 'Plan 3 Monthly Price',
                'value' => '39',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_price_annual',
                'name' => 'Plan 3 Annual Price',
                'value' => '351',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_1',
                'name' => 'Plan 3 Feature 1',
                'value' => '<b>Unlimited</b> Projects',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_2',
                'name' => 'Plan 3 Feature 2',
                'value' => '<b>Unlimited</b> Customers',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_3',
                'name' => 'Plan 3 Feature 3',
                'value' => 'Scalable Bandwidth',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_4',
                'name' => 'Plan 3 Feature 4',
                'value' => '<b>Unlimited</b> FTP Login',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_5',
                'name' => 'Plan 3 Feature 5',
                'value' => '<b>24/7</b> Support',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_6',
                'name' => 'Plan 3 Feature 6',
                'value' => '<b>Unlimited</b> Storage',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_feature_7',
                'name' => 'Plan 3 Feature 7',
                'value' => 'Domain',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_button_text',
                'name' => 'Plan 3 Button Text',
                'value' => 'Get Started',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.plan_3_button_link',
                'name' => 'Plan 3 Button Link',
                'value' => 'javascript:void(0);',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page FAQ Section
            [
                'key' => 'landing.faq_title',
                'name' => 'FAQ Section Title',
                'value' => 'Frequently Asked Questions',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_description',
                'name' => 'FAQ Section Description',
                'value' => 'If you can not find answer to your question in our FAQ, you can always contact us or email us. We will answer you shortly!',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_email_button_text',
                'name' => 'FAQ Email Button Text',
                'value' => 'Email Us',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_email_button_icon',
                'name' => 'FAQ Email Button Icon',
                'value' => 'ri-mail-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_email_button_link',
                'name' => 'FAQ Email Button Link',
                'value' => 'mailto:support@example.com',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_tweet_button_text',
                'name' => 'FAQ Tweet Button Text',
                'value' => 'Send Us Tweet',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_tweet_button_icon',
                'name' => 'FAQ Tweet Button Icon',
                'value' => 'ri-twitter-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_tweet_button_link',
                'name' => 'FAQ Tweet Button Link',
                'value' => 'https://twitter.com/example',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // General Questions Section
            [
                'key' => 'landing.faq_general_title',
                'name' => 'FAQ General Questions Title',
                'value' => 'General Questions',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_icon',
                'name' => 'FAQ General Questions Icon',
                'value' => 'ri-question-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_1_question',
                'name' => 'FAQ General Question 1',
                'value' => 'What is the purpose of using themes ?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_1_answer',
                'name' => 'FAQ General Answer 1',
                'value' => 'A theme is a set of colors, fonts, effects, and more that can be applied to your entire presentation to give it a consistent, professional look. You\'ve already been using a theme, even if you didn\'t know it: the default Office theme, which consists.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_2_question',
                'name' => 'FAQ General Question 2',
                'value' => 'Can a theme have more than one theme?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_2_answer',
                'name' => 'FAQ General Answer 2',
                'value' => 'A story can have as many themes as the reader can identify based on recurring patterns and parallels within the story itself. In looking at ways to separate themes into a hierarchy, we might find it useful to follow the example of a single book.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_3_question',
                'name' => 'FAQ General Question 3',
                'value' => 'What are theme features?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_3_answer',
                'name' => 'FAQ General Answer 3',
                'value' => 'Theme features is a set of specific functionality that may be enabled by theme authors. Themes must register each individual Theme Feature that the author wishes to support. Theme support functions should be called in the theme\'s functions.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_4_question',
                'name' => 'FAQ General Question 4',
                'value' => 'What is simple theme?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_general_4_answer',
                'name' => 'FAQ General Answer 4',
                'value' => 'Simple is a free WordPress theme, by Themify, built exactly what it is named for: simplicity. Immediately upgrade the quality of your WordPress site with the simple theme To use the built-in Chrome theme editor.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Privacy & Security Section
            [
                'key' => 'landing.faq_privacy_title',
                'name' => 'FAQ Privacy & Security Title',
                'value' => 'Privacy & Security',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_icon',
                'name' => 'FAQ Privacy & Security Icon',
                'value' => 'ri-shield-keyhole-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_1_question',
                'name' => 'FAQ Privacy Question 1',
                'value' => 'Does Word have night mode?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_1_answer',
                'name' => 'FAQ Privacy Answer 1',
                'value' => 'You can run Microsoft Word in dark mode, which uses a dark color palette to help reduce eye strain in low light settings. You can choose to make the document white or black using the Switch Modes button in the ribbon\'s View tab.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_2_question',
                'name' => 'FAQ Privacy Question 2',
                'value' => 'Is theme an opinion?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_2_answer',
                'name' => 'FAQ Privacy Answer 2',
                'value' => 'A theme is an opinion the author expresses on the subject, for instance, the author\'s dissatisfaction with the narrow confines of French bourgeois marriage during that period theme is an idea that a writer repeats.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_3_question',
                'name' => 'FAQ Privacy Question 3',
                'value' => 'How do you develop a theme?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_3_answer',
                'name' => 'FAQ Privacy Answer 3',
                'value' => 'A short story, novella, or novel presents a narrative to its reader. Perhaps that narrative involves mystery, terror, romance, comedy, or all of the above. These works of fiction may also contain memorable characters, vivid world-building, literary devices.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_4_question',
                'name' => 'FAQ Privacy Question 4',
                'value' => 'Do stories need themes?',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.faq_privacy_4_answer',
                'name' => 'FAQ Privacy Answer 4',
                'value' => 'A story can have as many themes as the reader can identify based on recurring patterns and parallels within the story itself. In looking at ways to separate themes into a hierarchy, we might find it useful to follow the example of a single book.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Reviews/Testimonials Section
            [
                'key' => 'landing.reviews_icon',
                'name' => 'Reviews Section Icon Class',
                'value' => 'ri-double-quotes-l',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.reviews_number',
                'name' => 'Reviews Section Number',
                'value' => '19k',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.reviews_heading',
                'name' => 'Reviews Section Heading',
                'value' => 'Satisfied clients',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Testimonial 1
            [
                'key' => 'landing.testimonial_1_quote',
                'name' => 'Testimonial 1 Quote',
                'value' => 'I am givng 5 stars. Theme is great and everyone one stuff everything in theme. Future request should not affect current state of theme.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_1_name',
                'name' => 'Testimonial 1 Name',
                'value' => 'gregoriusus',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_1_role',
                'name' => 'Testimonial 1 Role',
                'value' => 'Skote User',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Testimonial 2
            [
                'key' => 'landing.testimonial_2_quote',
                'name' => 'Testimonial 2 Quote',
                'value' => 'Awesome support. Had few issues while setting up because of my device, the support team helped me fix them up in a day. Everything looks clean and good. Highly recommended!',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_2_name',
                'name' => 'Testimonial 2 Name',
                'value' => 'GeekyGreenOwl',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_2_role',
                'name' => 'Testimonial 2 Role',
                'value' => 'Skote User',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Testimonial 3
            [
                'key' => 'landing.testimonial_3_quote',
                'name' => 'Testimonial 3 Quote',
                'value' => 'Amazing template, Redux store and components is nicely designed. It\'s a great start point for an admin based project. Clean Code and good documentation. Template is completely in React and absolutely no usage of jQuery',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_3_name',
                'name' => 'Testimonial 3 Name',
                'value' => 'sreeks456',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.testimonial_3_role',
                'name' => 'Testimonial 3 Role',
                'value' => 'Veltrix User',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Statistics/Counter Section
            [
                'key' => 'landing.stat_1_value',
                'name' => 'Statistic 1 Value',
                'value' => '100',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_1_suffix',
                'name' => 'Statistic 1 Suffix',
                'value' => '+',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_1_label',
                'name' => 'Statistic 1 Label',
                'value' => 'Projects Completed',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_2_value',
                'name' => 'Statistic 2 Value',
                'value' => '24',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_2_suffix',
                'name' => 'Statistic 2 Suffix',
                'value' => '',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_2_label',
                'name' => 'Statistic 2 Label',
                'value' => 'Win Awards',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_3_value',
                'name' => 'Statistic 3 Value',
                'value' => '20.3',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_3_suffix',
                'name' => 'Statistic 3 Suffix',
                'value' => 'k',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_3_label',
                'name' => 'Statistic 3 Label',
                'value' => 'Satisfied Clients',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_4_value',
                'name' => 'Statistic 4 Value',
                'value' => '50',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_4_suffix',
                'name' => 'Statistic 4 Suffix',
                'value' => '',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.stat_4_label',
                'name' => 'Statistic 4 Label',
                'value' => 'Employees',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page How Our System Works Section
            [
                'key' => 'landing.process_title',
                'name' => 'Process Section Title',
                'value' => 'How Our System Works',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_description',
                'name' => 'Process Section Description',
                'value' => 'Our enrollment and information management system streamlines your educational journey from start to finish. Here\'s a quick look at our simple, user-friendly process that ensures accuracy, transparency, and support at every stage.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_arrow_image',
                'name' => 'Process Arrow Image',
                'value' => 'build/images/landing/process-arrow-img.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_1_icon',
                'name' => 'Process Step 1 Icon',
                'value' => 'ri-quill-pen-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_1_title',
                'name' => 'Process Step 1 Title',
                'value' => 'Submit Your Information',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_1_description',
                'name' => 'Process Step 1 Description',
                'value' => 'Register and provide your personal and academic details through our secure portal. Our intuitive forms guide you to ensure your data is complete and accurate.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_2_icon',
                'name' => 'Process Step 2 Icon',
                'value' => 'ri-user-follow-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_2_title',
                'name' => 'Process Step 2 Title',
                'value' => 'Admin Review & Verification',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_2_description',
                'name' => 'Process Step 2 Description',
                'value' => 'Our administrators review your submission, verify the information, and assist if corrections are needed. Notifications keep you updated on the progress of your enrollment.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_3_icon',
                'name' => 'Process Step 3 Icon',
                'value' => 'ri-book-mark-line',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_3_title',
                'name' => 'Process Step 3 Title',
                'value' => 'Confirmation & Ongoing Access',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.process_3_description',
                'name' => 'Process Step 3 Description',
                'value' => 'Once approved, you\'ll receive confirmation and can access your enrollment information anytime. Manage updates, receive important notifications, and track your academic journey seamlessly!',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Our Team Section
            [
                'key' => 'landing.team_title',
                'name' => 'Team Section Title',
                'value' => 'Our Team',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_title_highlight',
                'name' => 'Team Section Title Highlight Text',
                'value' => 'Team',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_description',
                'name' => 'Team Section Description',
                'value' => 'Our talented team combines expertise in education and technology to build a smart, efficient system that empowers users. We are dedicated to continuous innovation, ensuring our platform makes enrollment and information management seamless, reliable, and easy for everyone.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_1_image',
                'name' => 'Team Member 1 Image',
                'value' => 'build/images/users/avatar-2.jpg',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_1_name',
                'name' => 'Team Member 1 Name',
                'value' => 'Nancy Martino',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_1_role',
                'name' => 'Team Member 1 Role',
                'value' => 'Team Leader',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_1_email',
                'name' => 'Team Member 1 Email',
                'value' => 'mailto:nancy@example.com',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_2_image',
                'name' => 'Team Member 2 Image',
                'value' => 'build/images/users/mark.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_2_name',
                'name' => 'Team Member 2 Name',
                'value' => 'Mark Vincent Quiao',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_2_role',
                'name' => 'Team Member 2 Role',
                'value' => 'Full Stack Developer',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_2_email',
                'name' => 'Team Member 2 Email',
                'value' => 'mailto:mark@example.com',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_3_image',
                'name' => 'Team Member 3 Image',
                'value' => 'build/images/users/kit.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_3_name',
                'name' => 'Team Member 3 Name',
                'value' => 'Kit Benedic Aguing',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_3_role',
                'name' => 'Team Member 3 Role',
                'value' => 'Project Manager',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_3_email',
                'name' => 'Team Member 3 Email',
                'value' => 'mailto:kit@example.com',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_4_image',
                'name' => 'Team Member 4 Image',
                'value' => 'build/images/users/cuyag.png',
                'type' => 'file',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_4_name',
                'name' => 'Team Member 4 Name',
                'value' => 'Saturnino JR E Cuyag',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_4_role',
                'name' => 'Team Member 4 Role',
                'value' => 'System Analyst',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.team_member_4_email',
                'name' => 'Team Member 4 Email',
                'value' => 'mailto:saturnino@example.com',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],

            // Landing Page Contact Section
            [
                'key' => 'landing.contact_title',
                'name' => 'Contact Section Title',
                'value' => 'Get In Touch',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_description',
                'name' => 'Contact Section Description',
                'value' => 'We thrive when coming up with innovative ideas but also understand that a smart concept should be supported with faucibus sapien odio measurable results.',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_address_1_label',
                'name' => 'Contact Address 1 Label',
                'value' => 'Office Address 1:',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_address_1',
                'name' => 'Contact Address 1',
                'value' => 'Kidapawan City,<br />North Cotabato',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_address_2_label',
                'name' => 'Contact Address 2 Label',
                'value' => 'Office Address 2:',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_address_2',
                'name' => 'Contact Address 2',
                'value' => 'Bansalan,<br />Davao del Sur',
                'type' => 'textarea',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_hours_label',
                'name' => 'Contact Working Hours Label',
                'value' => 'Working Hours:',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
            [
                'key' => 'landing.contact_hours',
                'name' => 'Contact Working Hours',
                'value' => '9:00am to 6:00pm',
                'type' => 'text',
                'group' => 'Landing Page',
                'is_locked' => false,
            ],
        ];

        foreach ($settings as $setting) {
            SystemSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
